/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package comshop;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.SQLException;
import java.util.TimerTask;
import java.util.Timer;
public class index extends javax.swing.JFrame {

    
    Connection conn;
    PreparedStatement pst1, pst;
    ResultSet rs, rs1;
    public index(String name) {
        initComponents();
        conn = db.conn();
        user.setText(name);
        String usernameDB = user.getText();
        String currentUSer;
        try{
            String sqlquery = "SELECT balance from user WHERE username =?";
            pst1 = conn.prepareStatement(sqlquery);
            pst1.setString(1,usernameDB);
            rs1 = pst1.executeQuery();
            if(rs1.next()){
                balance.setText(rs1.getString(1));
            }else{
                
            }
            
        }
        catch (SQLException e){
            
        }
        
       
    }
    private Timer timer;
private void startBalanceConsumptionTimer() {
    timer = new Timer();
    TimerTask task;
        task = new TimerTask() {
            @Override
            public void run() {
                String usernameDB = user.getText();
                try {
                    String sqlquery = "UPDATE user SET balance = balance - 1 WHERE username =? AND balance > 0";
                    pst = conn.prepareStatement(sqlquery);
                    pst.setString(1, usernameDB);
                    pst.executeUpdate();
                    
                    String get = "SELECT balance from user WHERE username =?";
                    pst1 = conn.prepareStatement(get);
                    pst1.setString(1, usernameDB);
                    rs1 = pst1.executeQuery();
                    if (rs1.next()) {
                        balance.setText(rs1.getString(1) + " php");
                    } else {
                        balance.setText("0 php");
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
                startBalanceConsumptionTimer();
            }
        };
    // Schedule the task to run every minute (60000 milliseconds)
    timer.scheduleAtFixedRate(task, 0, 60000);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_welcome1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(100);
        setFocusCycleRoot(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        user.setText("John");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 26, 209, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Balance: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 94, -1, -1));

        balance.setBackground(new java.awt.Color(255, 255, 255));
        balance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("100 php");
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 94, 57, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("25 PHP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 141, 276, 47));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("100 PHP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 385, 276, 47));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("50 PHP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 310, 276, 47));

        txt_welcome1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_welcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_welcome1.setText("Welcome back,");
        getContentPane().add(txt_welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 26, -1, 50));

        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-690, -540, -1, 360));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vits & Friends Internet Cafe.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -70, 1960, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String usernameDB = user.getText();
        String currentUSer;
        try{
            String sqlquery = "UPDATE user SET balance = balance + 50 WHERE username =?";
            pst = conn.prepareStatement(sqlquery);
            pst.setString(1,usernameDB);
            pst.executeUpdate();
          
              try{
                String get = "SELECT balance from user WHERE username =?";
                pst1 = conn.prepareStatement(get);
                pst1.setString(1,usernameDB);
                rs1 = pst1.executeQuery();
            if(rs1.next()){
                balance.setText(rs1.getString(1));
            }else{
                
            }
            
            }
            catch (SQLException e){

            }
        }
        catch (SQLException e){
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usernameDB = user.getText();
        String currentUSer;
        try{
            String sqlquery = "UPDATE user SET balance = balance + 25 WHERE username =?";
            pst = conn.prepareStatement(sqlquery);
            pst.setString(1,usernameDB);
            pst.executeUpdate();
          
           try{
                String get = "SELECT balance from user WHERE username =?";
                pst1 = conn.prepareStatement(get);
                pst1.setString(1,usernameDB);
                rs1 = pst1.executeQuery();
            if(rs1.next()){
                balance.setText(rs1.getString(1));
            }else{
                
            }
            
            }
            catch (SQLException e){

            }
        }
        catch (SQLException e){
            
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String usernameDB = user.getText();
        String currentUSer;
        try{
            String sqlquery = "UPDATE user SET balance = balance + 100 WHERE username =?";
            pst = conn.prepareStatement(sqlquery);
            pst.setString(1,usernameDB);
            pst.executeUpdate();
          
              try{
                String get = "SELECT balance from user WHERE username =?";
                pst1 = conn.prepareStatement(get);
                pst1.setString(1,usernameDB);
                rs1 = pst1.executeQuery();
            if(rs1.next()){
                balance.setText(rs1.getString(1));
            }else{
                
            }
            
            }
            catch (SQLException e){

            }
        }
        catch (SQLException e){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        loginF login = new loginF();
        this.setVisible(false);
        login.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed
     
     
    
    /**
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index(null).setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel txt_welcome1;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

   
}


